services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=website
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  Memcached:
    image: memcached
    ports:
      - "11211:11211"

  web:
    build: .
    command: gunicorn edu.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=edu.settings.pro
      - POSTGRES_NAME=website
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    entrypoint: /entrypoint.sh
    depends_on:
      - db

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/code
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  daphne:
    build: .
    working_dir: /code/
    command: daphne -u /code/daphne.sock edu.asgi:application
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=edu.settings.pro
      - POSTGRES_NAME=website
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
